name: todo_mongo
description: palace with mongo example
version: 1.0.0
publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  palace:
    path: ../../
  mongo_dart: ^0.7.0-nullsafety.3
dev_dependencies:
  pedantic: ^1.9.0
